#include "credits.h"
#include <SDL2/SDL_blendmode.h> // for SDL_BLENDMODE_BLEND
#include <SDL2/SDL_error.h>		// for SDL_GetError
#include <SDL2/SDL_events.h>	// for SDL_PollEvent, SDL_Event
#include <SDL2/SDL_pixels.h>	// for SDL_PIXELFORMAT_RGBA8888
#include <SDL2/SDL_rect.h>		// for SDL_Rect
#include <SDL2/SDL_timer.h>		// for SDL_GetTicks
#include <algorithm>			// for min
#include <iostream>				// for basic_ostream, operator<<, cout, endl
#include "s_animated_sprite.h"	// for SAnimatedSprite
#include "defines.h"			// for GAMECANVAS_HEIGHT, GAMECANVAS_WIDTH
#include "global_events.h"		// for check
#include "global_inputs.h"		// for check
#include "options.h"			// for Options, options, OptionsVideo, Sect...
#include "resource.h"			// for Resource
#include "screen.h"				// for Screen
#include "text.h"				// for Text, TEXT_CENTER, TEXT_COLOR

// Constructor
Credits::Credits()
	: shining_sprite_(std::make_shared<SAnimatedSprite>(Resource::get()->getSurface("shine.gif"), Resource::get()->getAnimations("shine.ani")))
{
	// Inicializa variables
	options.section.section = Section::CREDITS;
	options.section.subsection = Subsection::NONE;
	shining_sprite_->setPos({194, 174, 8, 8});

	// Cambia el color del borde
	Screen::get()->setBorderColor(stringToColor("black"));

	// Crea la textura para el texto que se escribe en pantalla
	text_surface_ = std::make_shared<Surface>(options.game.width, options.game.height);

	// Crea la textura para cubrir el rexto
	cover_surface_ = std::make_shared<Surface>(options.game.width, options.game.height);

	// Escribe el texto en la textura
	fillTexture();
}

// Comprueba el manejador de eventos
void Credits::checkEvents()
{
	SDL_Event event;
	while (SDL_PollEvent(&event))
	{
		globalEvents::check(event);
	}
}

// Comprueba las entradas
void Credits::checkInput()
{
	globalInputs::check();
}

// Inicializa los textos
void Credits::iniTexts()
{
#ifndef GAME_CONSOLE
	std::string keys = "";

	switch (options.keys)
	{
	case ControlScheme::CURSOR:
		keys = "CURSORS";
		break;
	case ControlScheme::OPQA:
		keys = "O,P AND Q";
		break;
	case ControlScheme::WASD:
		keys = "A,D AND W";
		break;
	default:
		break;
	}

	texts_.clear();
	texts_.push_back({"", stringToColor("white")});
	texts_.push_back({"INSTRUCTIONS:", stringToColor("yellow")});
	texts_.push_back({"", stringToColor("white")});
	texts_.push_back({"HELP JAILDOC TO GET BACK ALL", stringToColor("white")});
	texts_.push_back({"HIS PROJECTS AND GO TO THE", stringToColor("white")});
	texts_.push_back({"JAIL TO FINISH THEM", stringToColor("white")});
	texts_.push_back({"", stringToColor("white")});
	texts_.push_back({"", stringToColor("white")});

	texts_.push_back({"KEYS:", stringToColor("yellow")});
	texts_.push_back({"", stringToColor("white")});
	texts_.push_back({keys + " TO MOVE AND JUMP", stringToColor("white")});
	texts_.push_back({"M TO SWITCH THE MUSIC", stringToColor("white")});
	texts_.push_back({"H TO PAUSE THE GAME", stringToColor("white")});
	texts_.push_back({"F1-F2 TO CHANGE WINDOWS SIZE", stringToColor("white")});
	texts_.push_back({"F3 TO SWITCH TO FULLSCREEN", stringToColor("white")});
	texts_.push_back({"B TO TOOGLE THE BORDER SCREEN", stringToColor("white")});
	texts_.push_back({"", stringToColor("white")});
	texts_.push_back({"", stringToColor("white")});

	texts_.push_back({"A GAME BY JAILDESIGNER", stringToColor("yellow")});
	texts_.push_back({"MADE ON SUMMER/FALL 2022", stringToColor("yellow")});
	texts_.push_back({"", stringToColor("white")});
	texts_.push_back({"", stringToColor("white")});

	texts_.push_back({"I LOVE JAILGAMES! ", stringToColor("white")});
	texts_.push_back({"", stringToColor("white")});
#else
	texts.clear();
	texts.push_back({"", stringToColor("white")});
	texts.push_back({"INSTRUCTIONS:", stringToColor("yellow")});
	texts.push_back({"", stringToColor("white")});
	texts.push_back({"HELP JAILDOC TO GET BACK ALL", stringToColor("white")});
	texts.push_back({"HIS PROJECTS AND GO TO THE", stringToColor("white")});
	texts.push_back({"JAIL TO FINISH THEM", stringToColor("white")});
	texts.push_back({"", stringToColor("white")});
	texts.push_back({"", stringToColor("white")});

	texts.push_back({"KEYS:", stringToColor("yellow")});
	texts.push_back({"", stringToColor("white")});
	texts.push_back({"B TO JUMP", stringToColor("white")});
	texts.push_back({"R TO SWITCH THE MUSIC", stringToColor("white")});
	texts.push_back({"L TO SWAP THE COLOR PALETTE", stringToColor("white")});
	texts.push_back({"START TO PAUSE", stringToColor("white")});
	texts.push_back({"SELECT TO EXIT", stringToColor("white")});
	texts.push_back({"", stringToColor("white")});
	texts.push_back({"", stringToColor("white")});
	texts.push_back({"", stringToColor("white")});

	texts.push_back({"A GAME BY JAILDESIGNER", stringToColor("yellow")});
	texts.push_back({"MADE ON SUMMER/FALL 2022", stringToColor("yellow")});
	texts.push_back({"", stringToColor("white")});
	texts.push_back({"", stringToColor("white")});

	texts.push_back({"I LOVE JAILGAMES! ", stringToColor("white")});
	texts.push_back({"", stringToColor("white")});
#endif
}

// Escribe el texto en la textura
void Credits::fillTexture()
{
	// Inicializa los textos
	iniTexts();

	// Rellena la textura de texto
	Screen::get()->setRendererSurface(text_surface_);
	text_surface_->clear(stringToColor("black"));

	auto text = Resource::get()->getText("smb2");

	// Escribe el texto en la textura
	const int SIZE = text->getCharacterSize();
	int pos_y = 0;

	for (const auto &t : texts_)
	{
		text->writeDX(TEXT_CENTER | TEXT_COLOR, PLAY_AREA_CENTER_X, pos_y * SIZE, t.label, 1, t.color);
		pos_y++;
	}

	// Escribe el corazón
	const int TEXT_LENGHT = text->lenght(texts_[22].label, 1) - text->lenght(" ", 1); // Se resta el ultimo caracter que es un espacio
	const int POS_X = ((PLAY_AREA_WIDTH - TEXT_LENGHT) / 2) + TEXT_LENGHT;
	text->writeColored(POS_X, 176, "}", stringToColor("bright_red"));

	// Recoloca el sprite del brillo
	shining_sprite_->setPosX(POS_X + 2);
	Screen::get()->setRendererSurface(nullptr);

	// Rellena la textura que cubre el texto con color transparente
	Screen::get()->setRendererSurface(text_surface_);
	text_surface_->clear(stringToColor("transparent"));

	// Los primeros 8 pixels crea una malla
	auto surface = Screen::get()->getRendererSurface();
	auto color = stringToColor("black");
	for (int i = 0; i < 256; i += 2)
	{
		surface->putPixel(i, 0, color);
		surface->putPixel(i, 2, color);
		surface->putPixel(i, 4, color);
		surface->putPixel(i, 6, color);

		surface->putPixel(i + 1, 5, color);
		surface->putPixel(i + 1, 7, color);
	}

	// El resto se rellena de color sólido
	SDL_Rect rect = {0, 8, 256, 192};
	surface->fillRect(&rect, color);

	for (int i = 0; i < 256; i += 2)
	{
		surface->putPixel(i, 0, color);
		surface->putPixel(i, 2, color);
		surface->putPixel(i, 4, color);
		surface->putPixel(i, 6, color);

		surface->putPixel(i + 1, 5, color);
		surface->putPixel(i + 1, 7, color);
	}

	// El resto se rellena de color sólido
	rect = {0, 8, 256, 192};
	surface->fillRect(&rect, color);

	Screen::get()->setRendererSurface(nullptr);
}

// Actualiza el contador
void Credits::updateCounter()
{
	// Incrementa el contador
	if (counter_enabled_)
	{
		counter_++;
		if (counter_ == 224 || counter_ == 544 || counter_ == 672)
		{
			counter_enabled_ = false;
		}
	}
	else
	{
		sub_counter_++;
		if (sub_counter_ == 100)
		{
			counter_enabled_ = true;
			sub_counter_ = 0;
		}
	}

	// Comprueba si ha terminado la sección
	if (counter_ > 1200)
	{
		options.section.section = Section::DEMO;
	}
}

// Actualiza las variables
void Credits::update()
{
	// Comprueba que la diferencia de ticks sea mayor a la velocidad del juego
	if (SDL_GetTicks() - ticks_ > GAME_SPEED)
	{
		// Actualiza el contador de ticks
		ticks_ = SDL_GetTicks();

		// Comprueba las entradas
		checkInput();

		// Actualiza el contador
		updateCounter();

		Screen::get()->update();

		// Actualiza el sprite con el brillo
		if (counter_ > 770)
		{
			shining_sprite_->update();
		}
	}
}

// Dibuja en pantalla
void Credits::render()
{
	// Prepara para empezar a dibujar en la textura de juego
	Screen::get()->start();

	// Limpia la pantalla
	Screen::get()->clearSurface(1);

	if (counter_ < 1150)
	{
		// Dibuja la textura con el texto en pantalla
		text_surface_->render(0, 0);

		// Dibuja la textura que cubre el texto
		const int offset = std::min(counter_ / 8, 192 / 2);
		SDL_Rect srcRect = {0, 0, 256, 192 - (offset * 2)};
		cover_surface_->render(0, offset * 2, &srcRect);

		// Dibuja el sprite con el brillo
		shining_sprite_->render();
	}

	// Vuelca el contenido del renderizador en pantalla
	Screen::get()->render();
}

// Bucle para el logo del juego
void Credits::run()
{
	while (options.section.section == Section::CREDITS)
	{
		update();
		checkEvents();
		render();
	}
}